# Generated by Django 5.1.5 on 2025-02-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskteam',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='in_progress', max_length=20),
        ),
    ]
